### ISSUE TITLE
preprocessed dataset?

### ISSUE THREAD

**Issue by wubinbai** [kagaminccino/LAVSE#5]
I know we might need to download the Taiwan Mandarin Dataset, however, the preprocessed dataset in this repo. seems to be "wired"; any code to generate those files? especially the .pt ones.

**Comment by kagaminccino** [comment]
Hi,

Please refer to https://github.com/kagaminccino/LAVSE/issues/2 for the required information.
I left the institution a while ago and am no longer working on this project.
If further help is needed, please reach out to the current project member.
